"""Empowerment Applier — writes diagnostic results into agent configs.

Takes dimension analysis results and applies them as concrete improvements:
- MiMo: writes feedback file for next session
- Hermes: writes skill files and memory entries
- SYNTHEX: writes mechanism guidance and state files

Based on: ARSI Whitepaper §7.6 (Empowerment Engine)
"""
from __future__ import annotations

import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from arsi.foundation.store import MnemosyneStore

logger = logging.getLogger(__name__)


class EmpowermentApplier:
    """Applies dimension analysis results to agent configurations."""

    def __init__(self, store: MnemosyneStore):
        self.store = store
        self._application_count = 0

    def apply_all(self, dim_results: dict, agent_id: str = "all") -> dict:
        """Apply all dimension recommendations to appropriate agents."""
        applications = []

        for dim_name, result in dim_results.items():
            if "error" in result:
                continue

            sense = result.get("sense", {})
            gen = result.get("generate", {})
            if not sense.get("gap_detected"):
                continue

            action = gen.get("action", "none")
            if action == "none":
                continue

            # Apply to appropriate agent based on dimension
            app_result = self._apply_dimension(dim_name, gen, sense, agent_id)
            if app_result:
                applications.append(app_result)

        self._application_count += len(applications)

        return {
            "applied": len(applications),
            "applications": applications,
            "timestamp": datetime.now().isoformat(),
        }

    def _apply_dimension(self, dim_name: str, gen: dict, sense: dict, agent_id: str) -> Optional[dict]:
        """Apply a single dimension's recommendation."""
        try:
            if dim_name == "metacognition":
                return self._apply_metacognition(gen, sense)
            elif dim_name == "calibration":
                return self._apply_calibration(gen, sense)
            elif dim_name == "knowledge":
                return self._apply_knowledge(gen, sense)
            elif dim_name == "environment":
                return self._apply_environment(gen, sense)
            elif dim_name == "decomposition":
                return self._apply_decomposition(gen, sense)
            else:
                return self._apply_generic(dim_name, gen, sense)
        except Exception as e:
            logger.error(f"Failed to apply {dim_name}: {e}")
            return None

    def _apply_metacognition(self, gen: dict, sense: dict) -> dict:
        """Apply metacognitive rules to agents."""
        wasted = sense.get("wasted_attempts", 0)
        recommendation = gen.get("recommendation", "连续失败 2 次后切换策略")

        # Write to Hermes as a skill
        skill_content = f"""---
name: metacognitive-stopping-rules
description: ARSI-generated stopping rules to prevent wasted attempts
generated: {datetime.now().isoformat()}
source: arsi-metacognition-analysis
---

# Metacognitive Stopping Rules

## Background
ARSI analysis detected {wasted} wasted attempts in recent behavior.
Pattern: agent kept trying the same approach despite repeated failures.

## Rules
1. **2-strike rule**: After 2 consecutive failures with the same approach, STOP and switch strategy
2. **Ask rule**: If uncertain after 1 attempt, ask for clarification instead of guessing
3. **Pivot rule**: If a task has failed 3 times with different approaches, escalate to human
4. **Timeout rule**: If a single step takes >2x expected time, reassess approach

## When to apply
- Any task with iterative attempts
- Debugging and troubleshooting
- Code repair tasks

## Evidence
- Wasted attempts detected: {wasted}
- Generated by ARSI metacognition dimension
- Source traces analyzed from: MiMo + Hermes + SYNTHEX
"""

        skill_dir = Path.home() / ".hermes" / "skills" / "arsi-metacognition"
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(skill_content, encoding="utf-8")

        # Also write to MiMo feedback
        self._append_feedback(f"\n## 元认知改进建议\n- {recommendation}\n- 浪费尝试次数: {wasted}\n")

        # Record in Mnemosyne
        self.store.write_memory(
            __import__("arsi.foundation.schema", fromlist=["MemoryRecord"]).MemoryRecord(
                zone=__import__("arsi.foundation.schema", fromlist=["MemoryZone"]).MemoryZone.EXPERIENCE,
                content=f"[empowerment] metacognition rules applied: {recommendation}",
                tags=["empowerment", "metacognition", "applied"],
                importance=0.8,
            )
        )

        return {
            "dimension": "metacognition",
            "action": "wrote_skill",
            "target": str(skill_dir),
            "recommendation": recommendation,
        }

    def _apply_calibration(self, gen: dict, sense: dict) -> dict:
        """Apply calibration adjustments."""
        ece = sense.get("ece", 0)
        recommendations = gen.get("recommendations", [])

        cal_content = f"""---
name: arsi-calibration-guide
description: ARSI-generated confidence calibration guide
generated: {datetime.now().isoformat()}
ece: {ece}
---

# Confidence Calibration Guide

## Current Status
Expected Calibration Error (ECE): {ece:.3f}
{"⚠ Significant miscalibration detected" if ece > 0.15 else "✓ Reasonably calibrated"}

## Calibration Adjustments
"""
        for rec in recommendations:
            cal_content += f"\n### {rec.get('bin', 'unknown')} bucket\n"
            cal_content += f"- Issue: {rec.get('issue', '?')}\n"
            cal_content += f"- Adjustment: {rec.get('adjustment', '?')}\n"

        cal_content += f"""
## General Rules
1. When claiming >80% confidence, verify with at least 2 independent checks
2. When uncertain, say "I'm not sure" instead of guessing
3. Track your own accuracy: claimed confidence vs actual outcomes
4. When confidence and evidence disagree, trust evidence

## Evidence
- ECE measured from {sense.get('total_samples', 0)} behavior traces
- Generated by ARSI calibration dimension
"""

        skill_dir = Path.home() / ".hermes" / "skills" / "arsi-calibration"
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(cal_content, encoding="utf-8")

        self._append_feedback(f"\n## 置信度校准\n- ECE: {ece:.3f}\n- 建议: {'需要校准' if ece > 0.15 else '校准良好'}\n")

        return {
            "dimension": "calibration",
            "action": "wrote_skill",
            "target": str(skill_dir),
            "ece": ece,
        }

    def _apply_knowledge(self, gen: dict, sense: dict) -> dict:
        """Apply knowledge injection recommendations."""
        high_fail = sense.get("high_fail_actions", [])
        knowledge_gap = sense.get("knowledge_gap", {})

        # Generate knowledge document
        kn_content = f"""---
name: arsi-knowledge-injection
description: ARSI-generated knowledge from failure analysis
generated: {datetime.now().isoformat()}
---

# Knowledge Injection from Failure Analysis

## High-Failure Actions Detected
"""
        for hf in high_fail[:5]:
            kn_content += f"- **{hf['action']}**: failure rate {hf['fail_rate']:.0%}\n"

        if knowledge_gap:
            kn_content += f"\n## Knowledge Gap\n"
            kn_content += f"- Missing: {knowledge_gap.get('missing_knowledge', '?')}\n"
            kn_content += f"- Evidence: {knowledge_gap.get('evidence', '?')}\n"
            kn_content += f"- Suggestion: {knowledge_gap.get('suggestion', '?')}\n"

        kn_content += f"""
## Recommendations
1. Before executing high-failure actions, verify prerequisites
2. Add validation steps after each critical operation
3. Keep a failure log to identify patterns
4. When an action fails, analyze WHY before retrying

## Evidence
- {len(high_fail)} high-failure actions identified
- Generated by ARSI knowledge dimension
"""

        skill_dir = Path.home() / ".hermes" / "skills" / "arsi-knowledge"
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(kn_content, encoding="utf-8")

        self._append_feedback(f"\n## 知识注入\n- 高失败动作: {len(high_fail)} 个\n")

        return {
            "dimension": "knowledge",
            "action": "wrote_skill",
            "target": str(skill_dir),
            "high_fail_count": len(high_fail),
        }

    def _apply_environment(self, gen: dict, sense: dict) -> dict:
        """Apply environment improvement recommendations."""
        weak_actions = sense.get("weak_actions", [])
        recommendation = gen.get("recommendation", "为薄弱操作补充必要参数和上下文")

        env_content = f"""---
name: arsi-environment-improvements
description: ARSI-generated environment improvement recommendations
generated: {datetime.now().isoformat()}
---

# Environment Improvements

## Weak Actions Detected
"""
        for wa in weak_actions[:5]:
            env_content += f"- **{wa['action']}**: success rate {wa.get('success_rate', 0):.0%}\n"

        env_content += f"""
## Recommendations
{recommendation}

## General Environment Rules
1. Ensure all required tools are available before starting tasks
2. Set up proper error handling and logging
3. Configure appropriate timeouts for long-running operations
4. Keep environment variables and paths consistent

## Evidence
- {len(weak_actions)} weak actions identified
- Generated by ARSI environment dimension
"""

        skill_dir = Path.home() / ".hermes" / "skills" / "arsi-environment"
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(env_content, encoding="utf-8")

        self._append_feedback(f"\n## 环境改进\n- 弱项操作: {len(weak_actions)} 个\n- 建议: {recommendation}\n")

        return {
            "dimension": "environment",
            "action": "wrote_skill",
            "target": str(skill_dir),
            "weak_count": len(weak_actions),
        }

    def _apply_decomposition(self, gen: dict, sense: dict) -> dict:
        """Apply decomposition strategy recommendations."""
        recommendation = gen.get("recommendation", "改进任务分解策略")
        issue_type = gen.get("issue_type", "unknown")

        decomp_content = f"""---
name: arsi-decomposition-guide
description: ARSI-generated task decomposition improvements
generated: {datetime.now().isoformat()}
issue_type: {issue_type}
---

# Task Decomposition Guide

## Issue Detected
Type: {issue_type}
Recommendation: {recommendation}

## Decomposition Rules
1. **Break large tasks into verifiable steps** - each step should have a clear success criterion
2. **Order matters** - do prerequisite steps first (e.g., run tests before modifying code)
3. **Verify between steps** - don't chain unverified steps
4. **Keep steps atomic** - each step should do ONE thing
5. **Document the plan** - write down the decomposition before starting

## Common Patterns
- Code: read → understand → plan → implement → test → verify
- Research: question → search → analyze → synthesize → validate
- Debugging: reproduce → isolate → diagnose → fix → verify

## Evidence
- Generated by ARSI decomposition dimension
"""

        skill_dir = Path.home() / ".hermes" / "skills" / "arsi-decomposition"
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(decomp_content, encoding="utf-8")

        self._append_feedback(f"\n## 任务分解改进\n- 问题类型: {issue_type}\n- 建议: {recommendation}\n")

        return {
            "dimension": "decomposition",
            "action": "wrote_skill",
            "target": str(skill_dir),
            "issue_type": issue_type,
        }

    def _apply_generic(self, dim_name: str, gen: dict, sense: dict) -> dict:
        """Generic application for other dimensions."""
        recommendation = gen.get("recommendation", gen.get("strategy", ""))
        self._append_feedback(f"\n## {dim_name} 改进建议\n- {recommendation}\n")
        return {
            "dimension": dim_name,
            "action": "wrote_feedback",
            "recommendation": recommendation,
        }

    def _append_feedback(self, content: str) -> None:
        """Append to MiMo feedback file."""
        feedback_dir = Path.home() / ".local" / "share" / "mimocode" / "memory" / "arsi_feedback"
        feedback_dir.mkdir(parents=True, exist_ok=True)
        feedback_file = feedback_dir / "latest_suggestions.md"

        existing = feedback_file.read_text(encoding="utf-8") if feedback_file.exists() else "# ARSI 赋能建议\n"
        existing += content
        feedback_file.write_text(existing, encoding="utf-8")

    @property
    def stats(self) -> dict:
        return {"application_count": self._application_count}
